In [2]:
import numpy as np

In [2]:
np.__version__

'1.26.2'

In [3]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2=np.array([[1,2],
                [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [6]:
array3d=np.array([[
    [1,2],
    [3,4]
],
    [
        [5,6],
        [7,8]
    ]
])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
array3d.shape

(2, 2, 2)

In [10]:
array3ex=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
array3ex.shape

(2, 3, 3)

In [16]:
array4d=np.array([
    [
        [
            [1,2],
            [3,4],
            [5,6]
        ],
        [
            [7,8],
            [9,10],
            [11,12]
        ],
        [
            [13,14],
            [15,16],
            [17,18]
        ]
    ],
    [
        [
            [19,20],
            [21,22],
            [23,24]
        ],
        [
            [25,26],
            [27,28],
            [29,30]
        ],
        [
            [31,32],
            [33,34],
            [35,36]
        ]
    ]
])
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [13]:
array4d.shape

(2, 3, 3, 2)

In [3]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [10]:
import numpy as np
arr=np.array([10,20,30,40,50])
mean_val=np.mean(arr)
std_dev=np.std(arr)
max_val=np.max(arr)
min_val=np.min(arr)
print(arr)
print("The Average is",mean_val)
print(f"The Standard Deviation is {std_dev:.2f}")
print("The Maximum Value is",max_val)
print("The Minimum Value is",min_val)

[10 20 30 40 50]
The Average is 30.0
The Standard Deviation is 14.14
The Maximum Value is 50
The Minimum Value is 10


In [14]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=np.dot(A,B)
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Matrix Multiplication (A X B):\n",C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A X B):
 [[19 22]
 [43 50]]


In [18]:
arrayex5.ndim

1

In [19]:
print(A.ndim)

2


In [22]:
array6=np.array([1,2,3,4,5],ndmin=2)
array6

array([[1, 2, 3, 4, 5]])

In [23]:
print(array6.ndim)

2


shape attribute \n
tells the number of elements in each dimension

In [24]:
arrex=np.array([1,2,3,4,5])
arrex.shape

(5,)

Access Array elements- array indexing is the same as accessing an array element. The indexes in NumPy array start with 0.

In [25]:
print(A[0][1])

2


In [26]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

the array will be promoted to float64 because 3.3 is a float, and making the whole array an integer would cause a loss of info

In [27]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [28]:
ch_arr2=np.array(['Supervised','unSupervised','sEMi-supervised','reinforcement'])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [3]:
'''Creating 2D array'''
array_attributes=np.array([[10,20,30],[40,50,60]])
array_attributes.ndim

2

In [4]:
array_attributes.shape

(2, 3)

In [5]:
array_attributes.dtype

dtype('int32')

In [6]:
array_attributes.itemsize

4

In [7]:
array_attributes.data

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.empty((1,3))

array([[1.04006832e-311, 0.00000000e+000, 4.94065646e-324]])

In [20]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.random.random((2,2))

array([[0.73349307, 0.72120505],
       [0.93298846, 0.92558879]])

In [28]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [26]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
a=np.arange(5)

In [31]:
a

array([0, 1, 2, 3, 4])

In [33]:
a[2]

2

In [34]:
a[2:4]

array([2, 3])

In [35]:
a[:4:2]=-999
a

array([-999,    1, -999,    3,    4])

In [36]:
a[::-1]

array([   4,    3, -999,    1, -999])

In [37]:
for i in a:
    print(i)

-999
1
-999
3
4


In [38]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])

In [39]:
a[1,3]

8

In [40]:
a[1][3]

8

In [41]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [42]:
lower_axes=a[1,:]
lower_axes

array([5, 6, 7, 8])

In [43]:
lower_axes.ndim

1

In [44]:
same_axes=a[1:2,:]

In [45]:
same_axes

array([[5, 6, 7, 8]])

In [46]:
same_axes.ndim

2

In [47]:
a[:,1]

array([ 2,  6, 10])

In [48]:
a[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [49]:
for row in a:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [50]:
for k in a.flat:
    print(k)

1
2
3
4
5
6
7
8
9
10
11
12
